# Generated by Django 4.2.6 on 2023-11-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(help_text='Ссылка, например about/ или http://foo.com/', max_length=200, unique=True),
        ),
    ]
